#!/bin/sh
exec docker run \
  --rm \
  -v "$PWD:/app:ro" \
  -e APP_DIR=/app \
  -e LOG_OPTS='HEAD ^317b627124a58befac04e0a84febff8eb89770fb' \
  registry.gitlab.com/systra/qeto/infra/git-secret-analyzer:1.1.0
