#!/bin/sh
set -e
cd "$(dirname "$0")"
if [ -z "$1" ]; then
    echo "You should specify the new application name as first argument" >&2
    exit 1
elif ! echo "$1" | grep -q '^[a-z_]\+$'; then
    echo "The new application name should be lower case only + underscore" >&2
    exit 1
fi
name="$1"
for f in \
    package.json \
    index.html \
    gettext-extract \
; do
    sed -ri "s/myapp/$name/g" "$f";
done
mv locale/myapp.pot "locale/$name.pot"
find locale -type f -name 'myapp.po' -exec mv '{}' "$(dirname '{}')/$name.po" \;
find . -type f -name '*.vue' -exec sed -ri "s/myapp/$name/g" '{}' \;
rm -rf .git
