<script setup lang="ts">
import { computed, ref, onMounted, watch, nextTick } from 'vue'
import { useRunStore } from '@src/store/run'
import { useUserStore } from '@src/store/user'
import { useGettext } from 'vue3-gettext'
import { SingleParam } from '@src/types/typesStore'
const { $gettext } = useGettext()
const runStore = useRunStore()
const userStore = useUserStore()

const parameters = computed(() => runStore.filteredParameters)
const info = computed(() => runStore.selectedInfo)

const scenariosList = computed(() => { return userStore.scenariosList })
const activeScenario = computed(() => { return userStore.scenario })

function removeDeletedScenarios () {
  // for $scenario field: remove selected scenario if not in the scen list anymore.
  for (const cat of parameters.value) {
    for (const item of cat.params) {
      if (item.items === '$scenarios') {
        const scenarios = scenariosList.value.map(el => el.scenario)
        if (Array.isArray(item.value)) {
          item.value = item.value.filter(name => scenarios.includes(name))
        } else {
          item.value = scenarios.includes(item.value) ? item.value : ''
        }
      }
    }
  }
}

onMounted(() => {
  removeDeletedScenarios()
})

function getItems(item: SingleParam): any[] | undefined {
  // give all scenario as items choice.
  // else return items in the json (item.items)
  if (item.items === '$scenarios') {
    return scenariosList.value.map(
      el => el.scenario).filter(
      scen => scen !== activeScenario.value)
  } else {
    return item.items
  }
}

// Hints and edition

const showHint = ref(false)
const editHint = ref(false)
const hintRefs = ref<Record<string, HTMLTextAreaElement>>({})
// we have 2 v-for and some v-if. finding the correct ref in an array is impossible
// So we set it in a dict with the 2 key.
// Function to dynamically set the hint ref by ID
const setHintRef = (el: any, key: number, itemKey: number) => {
  if (el) {
    const stringKey = String(key) + String(itemKey)
    hintRefs.value[stringKey] = el
  }
}

function dblclick(key: number, itemKey: number) {
  editHint.value = true
  // on next tick (not mounted yet) put on focus.
  const stringKey = String(key) + String(itemKey)
  nextTick(() => hintRefs.value[stringKey].focus())
}

watch(showHint, (val) => {
  if (!val) { editHint.value = false }
})

// resizable div
import { useResize } from '@src/composables/useResize'
const { panelHeight: height, panelDiv: resizableDiv, startResize } = useResize(0, 50, 50)

onMounted(() => {
  // get div size generated by vue/css as inital value
  // if too large. force it to 25% of window
  if (resizableDiv.value) {
    const windowHeight = (window.innerHeight)
    const ratio = height.value / windowHeight
    if (ratio > 0.25) height.value = 0.25 * windowHeight
  }
})

// Show all or colapse panels

function reset () {
  runStore.resetParameters()
}

const panel = ref([...Array(parameters.value.length).keys()].map((k, i) => i))

function expandAll () {
  if (panel.value.length < parameters.value.length) {
    panel.value = [...Array(parameters.value.length).keys()].map((k, i) => i)
  } else {
    panel.value = []
  }
}

type Rules = Record<string, any>

const rules: Rules = {
  required: (v: any) => v != null || $gettext('Required'),
  largerThanZero: (v: number) => v > 0 || $gettext('should be larger than 0'),
  nonNegative: (v: number) => v >= 0 || $gettext('should be larger or equal to 0'),
}

</script>
<template>
  <v-card
    class="card"
  >
    <v-card-title class="subtitle">
      {{ $gettext('Scenario Settings') }}
    </v-card-title>
    <div
      v-show="info"
      ref="resizableDiv"
      class="info-div"
      :style="{ height: height + 'px' }"
    >
      {{ info }}
    </div>
    <div
      v-show="info"
      class="drag-handle"
      @mousedown="startResize"
    />
    <div class="expansion">
      <v-form
        ref="form"
        validate-on="lazy"
      >
        <v-expansion-panels
          v-model="panel"
          multiple
        >
          <v-expansion-panel
            v-for="(group, key) in parameters"
            :key="key"
          >
            <v-expansion-panel-title class="categorie">
              {{ group.category }}
            </v-expansion-panel-title>
            <v-expansion-panel-text style="background-color:rgb(var(--v-theme-lightgrey));">
              <div
                v-if="group.info"
                class="categorie-info"
              >
                {{ group.info }}
              </div>
              <li
                v-for="(item, itemKey) in group.params"
                :key="itemKey"
                class="param-list"
              >
                <v-switch
                  v-if="typeof item.items === 'undefined' && typeof item.value == 'boolean'"
                  v-model="item.value"
                  color="primary"
                  density="compact"
                  class="pl-2"
                  hide-details
                  :label="$gettext(item.text)"
                  :persistent-hint="showHint"
                />
                <v-number-input
                  v-else-if="item.type == 'Number'"
                  v-model="item.value"
                  variant="outlined"
                  control-variant="stacked"
                  :type="item.type"
                  :precision="item.precision === undefined? null : item.precision"
                  :label="$gettext(item.text)"
                  :suffix="item.units"
                  hide-details
                  :rules="item.rules?.map((str) => rules[str])"
                />
                <v-text-field
                  v-else-if="typeof item.items === 'undefined' "
                  v-model="item.value"
                  variant="outlined"
                  hide-details
                  :type="item.type"
                  :label="$gettext(item.text)"
                  :suffix="item.units"
                  :rules="item.rules?.map((rule) => rules[rule])"
                />

                <v-select
                  v-else
                  v-model="item.value"
                  variant="outlined"
                  hide-details
                  :type="item.type"
                  :multiple="item?.multiple"
                  :items="getItems(item)"
                  :label="$gettext(item.text)"
                  :suffix="item.units"
                  :rules="item.rules?.map((rule) => rules[rule])"
                  @update:model-value="removeDeletedScenarios()"
                />
                <v-fade-transition>
                  <div
                    v-if="showHint"
                    class="custom-hint"
                  >
                    <div
                      v-if="!editHint"
                      @dblclick="dblclick(key, itemKey)"
                    >
                      {{ item.hint }}
                    </div>
                    <textarea
                      v-else
                      :ref="el => setHintRef(el, key, itemKey)"
                      v-model="item.hint"
                      rows="1"
                      class="edition"
                      @keydown.enter="editHint=false"
                    />
                  </div>
                </v-fade-transition>
              </li>
            </v-expansion-panel-text>
          </v-expansion-panel>
        </v-expansion-panels>
      </v-form>
    </div>
    <v-card-actions>
      <v-btn
        color="grey"
        variant="text"
        @click="reset"
      >
        {{ $gettext("back to default") }}
      </v-btn>

      <v-spacer />
      <v-btn
        variant="text"
        @click="expandAll"
      >
        {{ panel.length != parameters.length ? $gettext("Expand all") : $gettext("Collapse all") }}
      </v-btn>
      <v-btn
        icon
        size="small"
        @click="showHint = !showHint"
      >
        <v-icon>far fa-question-circle small</v-icon>
      </v-btn>
    </v-card-actions>
  </v-card>
</template>
<style lang="scss" scoped>
// card style come from parent component.
.card {
  height: 100%;
  overflow-y: hidden;
  background-color: rgb(var(--v-theme-lightergrey));
}

.expansion{
  max-height:100%;
  overflow:hidden auto;
  flex-grow: 1;
  height:20rem;
}
.info-div{
  white-space: pre-line;
  overflow-y: scroll;
  padding: 1rem;
  margin-bottom:0

}
.drag-handle {
  height: 5px;
  background-color: rgb(var(--v-theme-darkgrey));
  margin: 2px;
  cursor: row-resize;
}
.subtitle {
  font-size: 2em;
  font-weight: bold;
}
.v-form {
  max-height: 80%;
}
.categorie {
  font-size: 1.5em;
  font-weight: bold;
  background: rgb(var(--v-theme-mediumgrey)) ;
}
.categorie-info{
  padding-bottom: 1rem;
  white-space: pre-line;
  font-size: small;
}
.param-list{
  margin-bottom:1.2rem;
}
.custom-hint{
  margin-left: 0.2rem;
  width:100%;
  min-height: 1.5rem;
  font-size:small;
  margin-right: auto;
}
.edition{
  border:1px gray solid;
  width:100%;
}

@media (width <= 768px) {
  .categorie {
    font-size: 1em;
  }
}
</style>
